project:
    name: MTBS

data:
    name: camvid
    # dir: G:\PyProjects\smp-seg-pytorch\data\CamVid
    useDataWoCAug: False
    CLASSES: ['car']

    random_state: 42
    SEED: 42

model:
    ARCH: DeepLabV3+
    ACTIVATION: sigmoid
    ENCODER: mobilenet_v2 # 'mobilenet_v2'
    ENCODER_WEIGHTS: imagenet
    INPUT_CHANNELS: 3

    max_epoch: 30
    batch_size: 8
    learning_rate: 1e-4
    weight_decay: 1e-4
    
    use_lr_scheduler: False
    warmup_coef: 2
    
    max_score: 0.1 # If IoU > max_score, start to save model
    verbose: True

experiment:
    note: dft
    name: ${data.name}_${model.ARCH}_${model.ENCODER}_${experiment.note}
    output: ./outputs/run_${experiment.name}_${now:%Y%m%dT%H%M%S} #${defaults.0.data}

hydra:
    run:
        dir: ${experiment.output}