project:
    name: MTBS

data:
    name: camvid
    useDataWoCAug: False
    CLASSES: ['car']

    random_state: 42

model:
    ARCH: UNet
    ACTIVATION: sigmoid
    ENCODER: resnet18 # 'mobilenet_v2'
    ENCODER_WEIGHTS: imagenet

    max_epoch: 50
    batch_size: 32
    learning_rate: 0.1
    weight_decay: 1e-4
    

    use_lr_scheduler: True
    warmup_coef: 2
    

    max_score: 0.1 # If IoU > max_score, start to save model

    verbose: True

experiment:
    note: dft
    name: ${data.name}_${model.ARCH}_${model.ENCODER}_${experiment.note}
    output: ./outputs/run_${now:%Y%m%dT%H%M%S}_${experiment.name} #${defaults.0.data}

hydra:
    run:
        dir: ${experiment.output}