project:
    name: MTBS

data:
    name: mtbs
    useDataWoCAug: False
    CLASSES: ['unburn', 'low', 'moderate', 'high', 'greener', 'cloud']
    SEED: 42
    random_state: 42

model:
    ARCH: UNet
    ACTIVATION: sigmoid
    ENCODER: resnet18 # 'mobilenet_v2'
    ENCODER_WEIGHTS: imagenet
    INPUT_CHANNELS: 12

    max_epoch: 10
    batch_size: 16
    learning_rate: 1e-4
    weight_decay: 1e-4
    

    use_lr_scheduler: False
    warmup_coef: 2
    
    max_score: 0.1 # If IoU > max_score, start to save model

    verbose: True

experiment:
    note: dft
    name: ${data.name}_${model.ARCH}_${model.ENCODER}_${experiment.note}
    output: ./outputs/run_${experiment.name}_${now:%Y%m%dT%H%M%S} #${defaults.0.data}

hydra:
    run:
        dir: ${experiment.output}