project:
    name: S1S2

data:
    name: s1s2
    satellites: ['S1', 'S2']
    dir: D:\wildfire-s1s2-dataset-ak-tiles
    useDataWoCAug: False
    SEED: 42
    CLASSES: ['unburn', 'burned']

    random_state: 42

model:
    ARCH: FuseUNet
    ACTIVATION: sigmoid
    ENCODER: resnet18 # 'mobilenet_v2'
    ENCODER_WEIGHTS: imagenet

    S1_INPUT_BANDS: ['ND', 'VH', 'VV']
    ALOS_INPUT_BANDS: ['ND', 'VH', 'VV']
    S2_INPUT_BANDS: ['B2', 'B3', 'B4', 'B8', 'B11', 'B12']
    REF_MASK: poly

    max_epoch: 20
    batch_size: 12
    learning_rate: 1e-4
    weight_decay: 1e-4
    cross_domain_coef: 0.1
    

    use_lr_scheduler: False
    warmup_coef: 2
    
    max_score: 0.1 # If IoU > max_score, start to save model

    verbose: True

experiment:
    note: fuse-mse
    name: ${data.name}_${model.ARCH}_${model.ENCODER}_${experiment.note}
    output: ./outputs/run_${experiment.name}_${now:%Y%m%dT%H%M%S} #${defaults.0.data}

hydra:
    run:
        dir: ${experiment.output}