project:
    name: S1S2

data:
    name: s1s2
    satellite: ALOS
    dir: D:\wildfire-s1s2-dataset-ak-tiles
    useDataWoCAug: False
    SEED: 42
    CLASSES: ['unburn', 'burned']

    random_state: 42

model:
    ARCH: UNet
    ACTIVATION: sigmoid
    ENCODER: resnet18 # 'mobilenet_v2'
    ENCODER_WEIGHTS: imagenet
    INPUT_CHANNELS: 6

    max_epoch: 100
    batch_size: 32
    learning_rate: 1e-4
    weight_decay: 1e-4
    

    use_lr_scheduler: False
    warmup_coef: 2
    
    max_score: 0.1 # If IoU > max_score, start to save model

    verbose: True

experiment:
    note: ${data.satellite}
    name: ${data.name}_${model.ARCH}_${model.ENCODER}_${experiment.note}
    output: ./outputs/run_${experiment.name}_${now:%Y%m%dT%H%M%S} #${defaults.0.data}

hydra:
    run:
        dir: ${experiment.output}