project:
    name: s1s2-snic-test
    entity: wildfire

data:
    # dir: /cephyr/NOBACKUP/groups/snic2021-7-104/wildfire-s1s2-dataset-ak-tiles
    # dir: /cephyr/NOBACKUP/groups/snic2021-7-104/wildfire-s1s2-dataset-ak-tiles
    # dir: /cephyr/NOBACKUP/groups/snic2021-7-104/puzhao-snic-500G/US_2021_Dixie
    dir: /cephyr/NOBACKUP/groups/snic2021-7-104/puzhao-snic-500G/CA_2021_Kamloops
    # dir: D:\wildfire-s1s2-dataset-ak-tiles

    name: s1s2
    satellites: ['S1']
    prepost: ['pre', 'post']
    stacking: True

    ALL_BANDS:
        S1: ['ND', 'VH', 'VV']
        ALOS: ['ND', 'VH', 'VV']
        S2: ['B2', 'B3', 'B4', 'B8', 'B11', 'B12']

    INPUT_BANDS:
        S1: ['ND', 'VH', 'VV']
        ALOS: ['ND', 'VH', 'VV']
        S2: ['B8', 'B11', 'B12']

    useDataWoCAug: False
    SEED: 42
    random_state: 42

    CLASSES: ['unburn', 'burned']
    REF_MASK: poly
    
    USE_PRE_IMG: True

model:
    ARCH: UNet #FuseUNet, UNet
    ACTIVATION: sigmoid
    ENCODER: resnet18 # 'mobilenet_v2'
    ENCODER_WEIGHTS: imagenet

    max_epoch: 20
    batch_size: 64
    learning_rate: 1e-4
    weight_decay: 1e-4
    cross_domain_coef: 0

    use_lr_scheduler: True
    warmup_coef: 2
    
    max_score: 0.1 # If IoU > max_score, save model
    verbose: True

eval:
    patchsize: 512

experiment:
    note: ${data.satellites}_to_Kam_prg
    name: ${data.name}_${model.ARCH}_${model.ENCODER}_${experiment.note}
    output: ./outputs/run_${experiment.name}_${now:%Y%m%dT%H%M%S} #${defaults.0.data}

hydra:
    run:
        dir: ${experiment.output}