
# defaults:
#     - s1s2_unet: s1

PROJECT:
    NAME: IGARSS-2022
    ENTITY: wildfire

RAND: # Rrproduce Results
    SEED: 42
    DETERMIN: True

DATA:
    NAME: s1s2
    DIR: /home/p/u/puzhao/wildfire-s1s2-dataset-ca-tiles
    # DIR: /cephyr/NOBACKUP/groups/snic2021-7-104/wildfire-s1s2-dataset-ak-tiles
    # DIR: /cephyr/NOBACKUP/groups/snic2021-7-104/wildfire-s1s2-dataset-ca-tiles

    SATELLITES: ['S1']
    PREPOST: ['pre','post']
    STACKING: True # stack bi-temporal data

    ALL_BANDS:
        ALOS: ['ND', 'VH', 'VV']
        S1: ['ND', 'VH', 'VV']
        S2: ['B2', 'B3', 'B4', 'B8', 'B11', 'B12']

    INPUT_BANDS:
        ALOS: ['ND', 'VH', 'VV']
        S1: ['ND', 'VH', 'VV']
        S2: ['B2', 'B3', 'B4', 'B8', 'B11', 'B12'] #['B4', 'B8', 'B12']
        # S2: ['B3', 'B8', 'B12'] #['B4', 'B8', 'B12']

    REF_MASK: poly
    TRAIN_RATIO: 0.9

MODEL:
    DEBUG: True

    AARCH: SiamUnet_conc #Paddle_unet #FuseUNet #FuseUNet, UNet
    SHARE_ENCODER: True

    TOPO: [16, 32, 64, 128]
    USE_DECONV: True
    LOSS_TYPE: DiceLoss # DiceLoss
    NUM_CLASSES: 1
    ACTIVATION: sigmoid #sigmoid

    ENCODER: resnet18 # 'mobilenet_v2'
    ENCODER_DEPTH: 4
    ENCODER_WEIGHTS: null

    MAX_EPOCH: 100
    BATCH_SIZE: 16

    LEARNING_RATE: 1e-4
    WEIGHT_DECAY: 1e-3
    LR_SCHEDULER:  poly # ['cosine', 'poly']
    POLY_SCHEDULER:
        END_LR: 1e-5
        POWER: 0.9
    COSINE_SCHEDULER:
        WARMUP: 2
    
    MAX_SCORE: 0.1 # If IoU > max_score, save model
    SAVE_INTERVAL: 5 # save model frequency
    STEP_WISE_LOG: False # log metrics every step/update
    VERBOSE: True

EVAL:
    PATCHSIZE: 512

EXP:
    NOTE: 
    NAME: ${DATA.NAME}_${MODEL.ARCH}_${DATA.SATELLITES}_${EXP.NOTE}
    OUTPUT: ./outputs/run_${EXP.NAME}_${now:%Y%m%dT%H%M%S} #${defaults.0.data}

hydra:
    run:
        dir: ${EXP.OUTPUT}