wandb_version: 1

DATA_ALL_BANDS_ALOS:
  desc: null
  value:
  - ND
  - VH
  - VV
DATA_ALL_BANDS_S1:
  desc: null
  value:
  - ND
  - VH
  - VV
DATA_ALL_BANDS_S2:
  desc: null
  value:
  - B2
  - B3
  - B4
  - B8
  - B11
  - B12
DATA_AUGMENT:
  desc: null
  value: false
DATA_DIR:
  desc: null
  value: /home/p/u/puzhao/wildfire-s1s2-dataset-ca-tiles
DATA_INPUT_BANDS_ALOS:
  desc: null
  value:
  - ND
  - VH
  - VV
DATA_INPUT_BANDS_S1:
  desc: null
  value:
  - ND
  - VH
  - VV
DATA_INPUT_BANDS_S2:
  desc: null
  value:
  - B4
  - B8
  - B12
DATA_NAME:
  desc: null
  value: s1s2
DATA_PREPOST:
  desc: null
  value:
  - pre
  - post
DATA_SATELLITES:
  desc: null
  value:
  - S1
DATA_STACKING:
  desc: null
  value: true
DATA_TEST_MASK:
  desc: null
  value: poly
DATA_TRAIN_MASK:
  desc: null
  value: poly
DATA_TRAIN_RATIO:
  desc: null
  value: 0.9
EVAL_PATCHSIZE:
  desc: null
  value: 512
EXP_FOLDER:
  desc: null
  value: Canada_RSE_2022
EXP_NAME:
  desc: null
  value: poly_UNet_['S1']_EF
EXP_NOTE:
  desc: null
  value: EF
EXP_OUTPUT:
  desc: null
  value: ./Canada_RSE_2022/run_poly_UNet_['S1']_EF_20220307T231359
MODEL_ACTIVATION:
  desc: null
  value: softmax
MODEL_ARCH:
  desc: null
  value: UNet
MODEL_BATCH_SIZE:
  desc: null
  value: 16
MODEL_CLASS_NAMES:
  desc: null
  value:
  - unburn
  - burned
MODEL_CLASS_WEIGHTS:
  desc: null
  value:
  - 0.5
  - 0.5
MODEL_COSINE_SCHEDULER_WARMUP:
  desc: null
  value: 10
MODEL_DEBUG:
  desc: null
  value: true
MODEL_ENCODER:
  desc: null
  value: resnet18
MODEL_ENCODER_DEPTH:
  desc: null
  value: 4
MODEL_ENCODER_WEIGHTS:
  desc: null
  value: imagenet
MODEL_LEARNING_RATE:
  desc: null
  value: 0.0001
MODEL_LOSS_TYPE:
  desc: null
  value: CrossEntropyLoss
MODEL_LR_SCHEDULER:
  desc: null
  value: cosine
MODEL_MAX_EPOCH:
  desc: null
  value: 5
MODEL_MAX_SCORE:
  desc: null
  value: 0.1
MODEL_NUM_CLASSES:
  desc: null
  value: 2
MODEL_POLY_SCHEDULER_END_LR:
  desc: null
  value: 1.0e-05
MODEL_POLY_SCHEDULER_POWER:
  desc: null
  value: 0.9
MODEL_SAVE_INTERVAL:
  desc: null
  value: 5
MODEL_STEP_WISE_LOG:
  desc: null
  value: false
MODEL_TOPO:
  desc: null
  value:
  - 16
  - 32
  - 64
  - 128
MODEL_USE_DECONV:
  desc: null
  value: false
MODEL_VERBOSE:
  desc: null
  value: true
MODEL_WEIGHT_DECAY:
  desc: null
  value: 0.01
PROJECT_ENTITY:
  desc: null
  value: wildfire
PROJECT_NAME:
  desc: null
  value: IGARSS-2022
RAND_DETERMIN:
  desc: null
  value: false
RAND_SEED:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.12
    start_time: 1646691240
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 13
      - 16
      4: 3.7.12
      5: 0.12.7
      8:
      - 2
      - 5
